import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
  type DocumentProps,
} from "@react-pdf/renderer";
import type { PdfReportPort } from "@/domain/agent/tools/pdf";
import { createAdminClient } from "../supabase/admin";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.45,
    color: "#1a1a1a",
  },
  title: {
    fontSize: 20,
    marginBottom: 16,
    fontFamily: "Helvetica-Bold",
  },
  paragraph: {
    marginBottom: 10,
  },
  heading: {
    fontSize: 14,
    marginTop: 14,
    marginBottom: 8,
    fontFamily: "Helvetica-Bold",
  },
  meta: {
    fontSize: 9,
    color: "#666",
    marginBottom: 24,
  },
});

function ReportDoc({ title, body }: { title: string; body: string }) {
  const blocks = body.split(/\n{2,}/);
  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(Text, { style: styles.title }, title),
      React.createElement(
        Text,
        { style: styles.meta },
        `Generated by MicroManus · ${new Date().toISOString().slice(0, 10)}`,
      ),
      ...blocks.map((block, i) => {
        const isHeading = block.startsWith("#");
        const text = block.replace(/^#+\s*/, "");
        return React.createElement(
          View,
          { key: i },
          React.createElement(
            Text,
            { style: isHeading ? styles.heading : styles.paragraph },
            text,
          ),
        );
      }),
    ),
  );
}

export function createPdfReportPort(): PdfReportPort {
  return {
    async createReport({ chatId, userId, title, markdown }) {
      const element = React.createElement(ReportDoc, {
        title,
        body: markdown,
      }) as React.ReactElement<DocumentProps>;
      const buffer = await renderToBuffer(element);
      const admin = createAdminClient();
      const path = `${userId}/${chatId}/${Date.now()}.pdf`;
      const { error: uploadError } = await admin.storage
        .from("artifacts")
        .upload(path, buffer, {
          contentType: "application/pdf",
          upsert: false,
        });
      if (uploadError) throw uploadError;

      const { data, error } = await admin
        .from("artifacts")
        .insert({
          chat_id: chatId,
          type: "pdf",
          title,
          storage_path: path,
        })
        .select("id")
        .single();
      if (error) throw error;

      return {
        artifactId: data.id as string,
        title,
        storagePath: path,
      };
    },
  };
}
